/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("de.brendamour.java-conventions")
}

dependencies {
    api(project(":jpasskit"))
    api(libs.org.restlet.jse.org.restlet)
    api(libs.org.restlet.jse.org.restlet.ext.simple)
}

description = "Java Server Example for Apple PassBook Web Service API"

java {
    withJavadocJar()
}
