/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    `jvm-test-suite`
    signing
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.restlet.talend.com")
    }
}

group = "de.brendamour"
version = "0.4.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11
extra["isReleaseVersion"] = !version.toString().endsWith("SNAPSHOT")

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

signing {
    sign(publishing.publications["maven"])
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion = "8.5"
}
tasks.register("prepareKotlinBuildScriptModel"){}